name: Create single html file

# Workflow startet bei Push in den Hauptbranch
on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run script
      - name: Execute custom script
        run: ./generate-single-html.sh
